import { YOLO } from 'https://esm.sh/@ultralytics/yolo@0.0.49';
const video=document.querySelector('#camera'),canvas=document.querySelector('#overlay'),ctx=canvas.getContext('2d'),cropCanvas=document.querySelector('#cropCanvas'),cropCtx=cropCanvas.getContext('2d'),$=s=>document.querySelector(s);
const startBtn=$('#startBtn'),switchBtn=$('#switchBtn'),fullscreenBtn=$('#fullscreenBtn'),liveBadge=$('#liveBadge'),emptyState=$('#emptyState'),message=$('#message'),systemStatus=$('#systemStatus'),detectedEl=$('#detected'),plateCountEl=$('#plateCount'),aiState=$('#aiState'),aiBadge=$('#aiBadge'),lastPlate=$('#lastPlate'),readsEl=$('#reads');
const PLATE_MODEL='https://huggingface.co/ml-debi/yolov8-license-plate-detection/resolve/main/best.onnx';
let stream=null,facingMode='environment',vehicleModel=null,plateModel=null,worker=null,running=false,timer=null,plateBusy=false,ocrBusy=false,lastPlateRun=0,lastOcr=0,reads=[],latestVehicles=[],latestPlates=[];const VEHICLES=new Set(['car','motorcycle','bus','truck']);
const LETTER_FROM_DIGIT={0:'O',1:'I',2:'Z',5:'S',6:'G',8:'B'},DIGIT_FROM_LETTER={O:'0',Q:'0',D:'0',I:'1',L:'1',Z:'2',S:'5',G:'6',B:'8'};
function msg(t){message.textContent=t;message.hidden=false}function clearMsg(){message.hidden=true}function rawPlate(t){return t.toUpperCase().replace(/[^A-Z0-9]/g,'').slice(0,12)}function asLetter(c){return /[A-Z]/.test(c)?c:(LETTER_FROM_DIGIT[c]||c)}function asDigit(c){return /\d/.test(c)?c:(DIGIT_FROM_LETTER[c]||c)}
function sgPlate(raw,vehicleClass='car'){const s=rawPlate(raw);let candidates=[];for(let prefixLen=1;prefixLen<=3;prefixLen++){for(let digits=1;digits<=4;digits++){const len=prefixLen+digits+1;if(s.length!==len)continue;let pre='',num='';for(let i=0;i<prefixLen;i++)pre+=asLetter(s[i]);for(let i=prefixLen;i<prefixLen+digits;i++)num+=asDigit(s[i]);const suffix=asLetter(s[len-1]);if(!/^[A-Z]+$/.test(pre)||!/^[1-9]\d{0,3}$/.test(num)||!/^[A-Z]$/.test(suffix))continue;let score=0;if(vehicleClass==='car'&&pre.startsWith('S'))score+=5;if(vehicleClass==='motorcycle'&&pre.startsWith('F'))score+=5;if((vehicleClass==='truck'||vehicleClass==='bus')&&/^[GXYPS]/.test(pre))score+=3;if(prefixLen===3)score+=2;if(!/[IO]/.test(pre))score+=1;if(!/[FINOQVW]/.test(suffix))score+=1;candidates.push({plate:pre+num+suffix,score,valid:true})}}return candidates.sort((a,b)=>b.score-a.score)[0]||{plate:s,score:0,valid:false}}
async function loadModels(){try{systemStatus.textContent='Loading vehicle detector…';await tf.ready();vehicleModel=await cocoSsd.load({base:'lite_mobilenet_v2'});aiState.textContent='Vehicle ready · loading plate AI';systemStatus.textContent='Loading dedicated plate detector…';plateModel=await YOLO.load(PLATE_MODEL,{device:'cpu'});aiState.textContent='Detectors ready · loading OCR';systemStatus.textContent='Loading OCR…';worker=await Tesseract.createWorker('eng',1,{logger:()=>{}});await worker.setParameters({tessedit_char_whitelist:'ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789',tessedit_pageseg_mode:'7'});aiState.textContent='SG plate intelligence ready';aiBadge.classList.add('ready');systemStatus.textContent='Ready — Singapore VRN rules active'}catch(e){console.error('Model load',e);aiState.textContent='Model load issue';systemStatus.textContent='One model failed to load';msg('V3.2 could not load every AI model. Refresh once.')}}
async function startCamera(){clearMsg();try{stopTracks();stream=await navigator.mediaDevices.getUserMedia({video:{facingMode:{ideal:facingMode},width:{ideal:1920},height:{ideal:1080}},audio:false});video.srcObject=stream;await video.play();liveBadge.classList.add('on');liveBadge.innerHTML='<span></span> LIVE';emptyState.classList.add('hide');startBtn.classList.add('stop');startBtn.querySelector('b').textContent='Stop Camera';switchBtn.disabled=false;systemStatus.textContent='Scanning Singapore plates…';resizeCanvas();running=true;loop()}catch(e){console.error(e);stopCamera();msg(e.name==='NotAllowedError'?'Camera permission denied.':'Could not access camera.')}}
function stopTracks(){if(stream){stream.getTracks().forEach(t=>t.stop());stream=null}}function stopCamera(){running=false;clearTimeout(timer);stopTracks();video.srcObject=null;ctx.clearRect(0,0,canvas.width,canvas.height);detectedEl.textContent='0';plateCountEl.textContent='0';latestVehicles=[];latestPlates=[];liveBadge.classList.remove('on');liveBadge.innerHTML='<span></span> OFFLINE';startBtn.classList.remove('stop');startBtn.querySelector('b').textContent='Start Camera';switchBtn.disabled=true;emptyState.classList.remove('hide');systemStatus.textContent=vehicleModel&&plateModel&&worker?'Ready — Singapore VRN rules active':'Loading detection models…'}
function resizeCanvas(){const r=video.getBoundingClientRect(),d=Math.min(devicePixelRatio||1,2);canvas.width=r.width*d;canvas.height=r.height*d;ctx.setTransform(d,0,0,d,0,0)}function mapVideoBox(b){const r=video.getBoundingClientRect(),s=Math.max(r.width/video.videoWidth,r.height/video.videoHeight),ox=(r.width-video.videoWidth*s)/2,oy=(r.height-video.videoHeight*s)/2;return[b[0]*s+ox,b[1]*s+oy,b[2]*s,b[3]*s]}
function draw(){const r=video.getBoundingClientRect();ctx.clearRect(0,0,r.width,r.height);latestVehicles.forEach(p=>{const[x,y,w,h]=mapVideoBox(p.bbox);ctx.strokeStyle='#57f1c5';ctx.lineWidth=2;ctx.strokeRect(x,y,w,h);ctx.fillStyle='#03100ee6';ctx.fillRect(x,Math.max(0,y-23),110,23);ctx.fillStyle='#57f1c5';ctx.font='700 11px system-ui';ctx.fillText(`${p.class.toUpperCase()} ${Math.round(p.score*100)}%`,x+6,Math.max(16,y-7))});latestPlates.forEach(p=>{const[x,y,w,h]=mapVideoBox(p.bbox);ctx.strokeStyle='#ffd45a';ctx.lineWidth=3;ctx.strokeRect(x,y,w,h);ctx.fillStyle='#ffd45a';ctx.fillRect(x,Math.max(0,y-21),Math.max(88,w),21);ctx.fillStyle='#101010';ctx.font='800 10px system-ui';ctx.fillText(`PLATE ${Math.round(p.conf*100)}%`,x+5,Math.max(14,y-6))});detectedEl.textContent=latestVehicles.length;plateCountEl.textContent=latestPlates.length}
function nearestVehicle(p){const pcx=p.bbox[0]+p.bbox[2]/2,pcy=p.bbox[1]+p.bbox[3]/2;return latestVehicles.filter(v=>pcx>=v.bbox[0]&&pcx<=v.bbox[0]+v.bbox[2]&&pcy>=v.bbox[1]&&pcy<=v.bbox[1]+v.bbox[3]).sort((a,b)=>a.bbox[2]*a.bbox[3]-b.bbox[2]*b.bbox[3])[0]||latestVehicles[0]}
async function detectPlates(){if(plateBusy||!plateModel||Date.now()-lastPlateRun<700)return;plateBusy=true;lastPlateRun=Date.now();try{const result=await plateModel.predict(video,{conf:.28,iou:.5});latestPlates=(result.boxes||[]).map(b=>({bbox:[b.x1,b.y1,b.x2-b.x1,b.y2-b.y1],conf:b.conf})).filter(p=>p.bbox[2]>=18&&p.bbox[3]>=7);draw();const best=[...latestPlates].sort((a,b)=>b.bbox[2]*b.bbox[3]-a.bbox[2]*a.bbox[3])[0];if(best)readPlate(best,nearestVehicle(best)?.class||'car')}catch(e){console.warn('Plate detector',e)}finally{plateBusy=false}}
async function readPlate(p,vehicleClass){if(ocrBusy||!worker||Date.now()-lastOcr<1600)return;ocrBusy=true;lastOcr=Date.now();try{let[x,y,w,h]=p.bbox;x=Math.max(0,x-4);y=Math.max(0,y-4);w=Math.min(w+8,video.videoWidth-x);h=Math.min(h+8,video.videoHeight-y);if(w<35||h<10)return;const scale=Math.min(7,Math.max(3,650/w));cropCanvas.width=Math.round(w*scale);cropCanvas.height=Math.round(h*scale);cropCtx.filter='grayscale(1) contrast(2.2)';cropCtx.drawImage(video,x,y,w,h,0,0,cropCanvas.width,cropCanvas.height);cropCtx.filter='none';systemStatus.textContent='Plate found — applying SG VRN rules…';const res=await worker.recognize(cropCanvas),raw=rawPlate(res.data.text),parsed=sgPlate(raw,vehicleClass);if(parsed.valid){addRead(parsed.plate,Math.round(res.data.confidence),raw!==parsed.plate);lastPlate.textContent=parsed.plate}else if(raw.length>=4){systemStatus.textContent=`OCR ${raw} rejected — not SG format`;setTimeout(()=>{if(running)systemStatus.textContent='Scanning Singapore plates…'},900);return}systemStatus.textContent='Scanning Singapore plates…'}catch(e){console.warn('OCR',e)}finally{ocrBusy=false}}
function addRead(plate,confidence,corrected){if(reads[0]?.plate===plate&&Date.now()-reads[0].ts<12000)return;reads.unshift({plate,confidence,corrected,ts:Date.now()});reads=reads.slice(0,8);renderReads()}function renderReads(){readsEl.innerHTML=reads.length?reads.map(r=>`<div class="read"><span class="plate-number">${r.plate}</span><span>${new Date(r.ts).toLocaleTimeString([],{hour:'2-digit',minute:'2-digit',second:'2-digit'})}</span><em>${r.corrected?'SG corrected · ':''}${r.confidence}% OCR</em></div>`).join(''):'<div class="no-reads">No valid Singapore plates read yet</div>'}
async function loop(){if(!running||!stream)return;if(!vehicleModel||video.readyState<2){timer=setTimeout(loop,250);return}try{const ps=await vehicleModel.detect(video,20,.35);latestVehicles=ps.filter(p=>VEHICLES.has(p.class)&&p.score>.42);draw();detectPlates()}catch(e){console.warn('Vehicle detector',e)}timer=setTimeout(loop,100)}
startBtn.onclick=()=>stream?stopCamera():startCamera();switchBtn.onclick=async()=>{facingMode=facingMode==='environment'?'user':'environment';await startCamera()};fullscreenBtn.onclick=async()=>{try{document.fullscreenElement?await document.exitFullscreen?.():await document.documentElement.requestFullscreen?.()}catch(e){}};$('#clearReads').onclick=()=>{reads=[];lastPlate.textContent='—';renderReads()};window.onresize=()=>stream&&resizeCanvas();window.addEventListener('pagehide',stopTracks);loadModels();